# Generated by Django 5.2.4 on 2025-08-01 14:11

import phonevalidatorGCC.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, unique=True, verbose_name='Full Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('phone_number', phonevalidatorGCC.fields.PhoneNumberField(help_text='Enter a valid Egyptian phone number.', max_length=11, unique=True, verbose_name='Phone Number')),
                ('subscription_plan', models.CharField(choices=[('1MONTH', '1 Month'), ('2MONTH', '2 Months'), ('3MONTH', '3 Months'), ('4MONTH', '4 Months'), ('5MONTH', '5 Months'), ('6MONTH', '6 Months'), ('7MONTH', '7 Months'), ('8MONTH', '8 Months'), ('9MONTH', '9 Months'), ('10MONTH', '10 Months'), ('11MONTH', '11 Months'), ('12MONTH', '12 Months')], default='1MONTH', max_length=20, verbose_name='Subscription Plan')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], max_length=25, verbose_name='Status')),
            ],
        ),
    ]
