# Generated by Django 5.2.4 on 2025-08-01 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='member',
            name='start_from',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Start Date'),
        ),
    ]
