# Generated by Django 5.2.4 on 2025-08-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_expiration_date_member_start_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_treadmale',
            field=models.BooleanField(default=False, verbose_name='Has Tread Male'),
        ),
        migrations.AddField(
            model_name='member',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price'),
        ),
    ]
