# Generated by Django 5.2.4 on 2025-08-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_gymexpense_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymexpense',
            options={'verbose_name': 'Gym Expense', 'verbose_name_plural': 'Gym Expenses'},
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, help_text='Add some notes for this member', null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo'),
        ),
    ]
