# Generated by Django 5.2.4 on 2025-08-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_gymexpense_options_member_notes_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
